import "./globals.css";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";

// components
import { NavBar } from "./components/nav-bar";
import { Footer } from "./components/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const roboto = Roboto({ weight: "400", subsets: ["latin"] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={roboto.className}>
      <body>
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
