import "./globals.css";
import type { Metadata } from "next";

// components
import { MuiNavBar } from "./components/mui-nav-bar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <MuiNavBar />
      <body>{children}</body>
    </html>
  );
}
